#ifndef HEADER_GUARD
#define HEADER_GUARD

// File generated by cgoStructGen - DO NOT EDIT
// Struct definitions generated for C from Go struct definitions

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

	typedef struct s1{
		int8_t f1;
		uint8_t f2;
		float f3;
		double f4;
		bool f5;
		char* f6;
	} s1_t;

	typedef struct s2{
		uint32_t f7[5];
		int32_t* f8;
		s1_t f9;
		s1_t f10[10];
		s1_t* f11;
	} s2_t;

#ifdef __cplusplus
}
#endif

#endif
